language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_84cd72d0ee10_key -iv $encrypted_84cd72d0ee10_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
